title: Siddharth Mundra
logo: assets/Photo_SidMundra.jpg
description: >
  Sophmore at UC San Diego majoring in Computer Science and minoring in Finance
  <br>
  <br>
  <b>Email: smundra@ucsd.edu</b>
  <br>
  <br>
  <a href="https://drive.google.com/file/d/1gd8npsWG9SeXYmAm7563CBT1CERumJXy/view?usp=sharing"><b>Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/siddharthmundra04">LinkedIn</a>
  <br>
  <br>
  <a href="https://stackoverflow.com/users/16408088/siddharth-mundra"><b>Stack Overflow</a>
  </b>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
