title: Siddharth Mundra
logo: assets/Photo_SidMundra.jpg
  Sophmore at UC San Diego majoring in Computer Science and minoring in Finance
  <br>
  <br>
  <b>Email: smundra@ucsd.edu</b>
  <br>
  <br>
  <a href="https://drive.google.com/file/d/1teDMtAYbe3HOxPKYSFXRoaXVif7T9IK2/view?usp=sharing"><b>Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/siddharthmundra04/">LinkedIn</a>
  <br>
  </b>
remote_theme: pages-themes/minimal@v0.2.0
